### ISSUE TITLE
(UI) Feed + Login + Add Post

### ISSUE THREAD

**Issue by JoeBosch** [CMPUT301F19T28/FeelsBook#11]
**Feed**
- add list of posts
- add post button
- feed/map slider
- profile button
- filter menu button

**Login**
- login button
- username and password fields

**Add Post**
- cancel button
- text field
- confirm button
- picture/mood/location/social situation buttons

**Comment by kbalisnomo** [comment]
Created all UML files for Feed + Login + Add Post.
Also looked into using a ViewPager for whenever we implement the feed/map slider
