### ISSUE TITLE
Basic implementation of FeedList/Homepage 

### ISSUE THREAD

**Issue by IzuEneh** [CMPUT301F19T28/FeelsBook#15]
Deploying Home page to contain feed and contain functionality for future homepage methods

**Comment by eclipse162** [comment]
Implementation to be done:
- complete links to linkToFirestoreNew with .xml files in KyleBranch
- structure the launch / finish activity sequence (ex. from LoginActivity -> SignUpActivity or MainActivity)
- display Feed of the user created inside of SignUpActivity

**Comment by IzuEneh** [comment]
structured transition from signup to main activity and sent user from login page to main activity
