### ISSUE TITLE
Individualize posts

### ISSUE THREAD

**Issue by eclipse162** [CMPUT301F19T28/FeelsBook#45]
For each Post created, a User will always be associated with each post. We need to somehow relate each Post to a User, either through a username or other means. This will make it easier to filter for specific Users and also to display relevant profile information.

TO-DO:
- inside AddPostFragment, when post is added, create a collection that stores Posts for that user
- instead of passing a List object to Profile, pass a User and display their Posts as their history list
- display the profile picture of the associated User in each Post
- (for later sprints) add an optional tag for mood type to each Post for filtering

**Comment by IzuEneh** [comment]
I feel like this would be better implemented using the database I'll try to do it with that

**Comment by IzuEneh** [comment]
completed
